name: meesign_network
description: Interface for communication with MeeSign Server using gRPC.
version: 0.3.0
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  fixnum: ^1.0.1
  grpc: ^3.2.0
  protobuf: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
