name: meesign_core
description: Core layer of MeeSign client shared by GUI and CLI.
version: 0.3.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.5.0
  collection: ^1.16.0
  convert: ^3.1.1
  drift: ^2.5.0
  meesign_native: {path: ../meesign_native}
  meesign_network: {path: ../meesign_network}
  meta: ^1.7.0
  path: ^1.8.1
  pub_semver: ^2.1.4
  rxdart: ^0.27.5
  synchronized: ^3.0.0+3

dev_dependencies:
  build_runner: ^2.3.3
  drift_dev: ^2.5.2
  lints: ^3.0.0
  test: ^1.16.0
